version: '3.8'

services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./db-data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    adminer:
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
            - 8081:8080
    # node:
    #     build: ./api
    #     ports:
    #     - "3000:3000"
    #     volumes:
    #     - ./api:/usr/src/app/
    #     - /usr/src/app/node_modules
    #     # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    #     depends_on:
    #         db:
    #             condition: service_healthy
    # frontend:
    #     # container_name: frontend
    #     build: ./front
    #     volumes:
    #     - ./front:/app
    #     - /app/node_modules
    #     ports:
    #     - '5173:5173'