version: '3.8'

services:
    db:
        image: postgres:13-alpine
        restart: always
        volumes:
            - ./db-data:/var/lib/postgresql/data
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432

    adminer:
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
            - 8081:8080
