version: '3.8'

services:
    db:
        image: postgres:latest
        restart: always
        volumes:
            - ./db-data:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
            interval: 5s
            timeout: 5s
            retries: 5
    adminer:
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
            - 8081:8080
    api:
        build: ./api
        restart: always
        env_file:
            - .env
        ports:
            - 3000:3000
        command: >
            sh -c "npx prisma generate
            && npx prisma db push --force-reset
            && npx prisma db seed
            && npm run start"
        depends_on:
            - db
        volumes:
            - .:/app
    vue:
        build: ./front
        restart: always
        ports:
            - 8080:80
        depends_on:
            - api
